name: {{class_name}}_api_client
description: A client to interact with the {{class_name}} API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  http: ^1.2.1
